### ISSUE TITLE
장바구니에 상품 추가 시 mapping 위치 의견

### ISSUE THREAD

**Issue by Robbie-Kim** [NC4Mini/NC4_mini_project-1.10-#23]
### 장바구니에 상품 추가 기능 관련

장바구니에 상품 정보를 받아서 entity로 전해줘야합니다. 이때 정보를 받는 위치가

1. Item의 Controller 에서 매핑해야 한다..?
2. Cart의 Controller 에서 매핑해야 한다..?

도움 !

**Comment by LeeMooho** [comment]
아키텍쳐의 차이로 구분될 수 있을 것 같습니다. 
![image.png](https://github.com/NC4Mini/NC4_mini_project-1.10-/assets/74390199/420914e8-b970-4e3b-b35a-15068d5b8fc2)

아키텍쳐를 마이크로서비스, 모놀리식에 따라 아이템과 카트의 기능을 합칠지 별도로 구현할지 정해지는데 MSA방식을 따르면

장바구니에 상품 정보를 담아서 cart entity에 전달하기 위해 Cart의 Controller 에서 매핑해야 한다고 생각합니다. 

다른 의견 있으시면 공유 부탁드립니다.
